# Generated by Django 4.2.11 on 2024-09-02 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('georeferencing', '0002_alter_imagegeoattempt_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlpoint',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
