# Generated by Django 4.2.11 on 2024-09-02 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georeferencing', '0003_controlpoint_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagegeoattempt',
            name='path',
            field=models.FilePathField(),
        ),
    ]
