# Generated by Django 4.2.11 on 2024-09-02 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georeferencing', '0005_remove_controlpoint_user_remove_imagegeoattempt_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagegeoattempt',
            name='hash',
            field=models.CharField(default='5e508b228683c57b4b51caaaa30a247a', max_length=100),
        ),
    ]
