# Generated by Django 4.2.11 on 2024-09-02 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('georeferencing', '0006_imagegeoattempt_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('path', models.FilePathField(path='/tmp/')),
                ('hash', models.CharField(default='46fa6d5ccc2ca438d80e7eee5702a8e8', max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('DOING', 'Doing'), ('SUCCESS', 'Success'), ('FAILURE', 'Failure')], default='PENDING', max_length=10)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='georeferencing.image')),
            ],
        ),
        migrations.RemoveField(
            model_name='controlpoint',
            name='ImageGeoAttempt',
        ),
        migrations.DeleteModel(
            name='ImageGeoAttempt',
        ),
        migrations.AddField(
            model_name='controlpoint',
            name='geoAttempt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='georeferencing.geoattempt'),
        ),
    ]
