# Generated by Django 4.2.11 on 2024-09-02 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georeferencing', '0007_geoattempt_remove_controlpoint_imagegeoattempt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geoattempt',
            name='hash',
            field=models.CharField(default='7641eabc4d33e36383bd5827a0a086ff', max_length=100),
        ),
    ]
