# Generated by Django 4.2.11 on 2024-09-02 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georeferencing', '0008_alter_geoattempt_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geoattempt',
            name='hash',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
