# Generated by Django 4.2.11 on 2024-09-21 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('georeferencing', '0010_image_camera_image_cameratilt_image_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='path',
        ),
    ]
