# Generated by Django 4.2.11 on 2024-09-21 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('georeferencing', '0011_remove_image_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geoattempt',
            name='path',
        ),
    ]
