# Generated by Django 4.2.11 on 2024-09-24 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georeferencing', '0012_remove_geoattempt_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geoattempt',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('DONE', 'Done')], default='PENDING', max_length=10),
        ),
    ]
