# Generated by Django 4.2.11 on 2024-09-24 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georeferencing', '0015_geoattempt_controlpoints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geoattempt',
            name='controlPoints',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
