# Generated by Django 4.2.11 on 2024-09-26 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georeferencing', '0016_alter_geoattempt_controlpoints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geoattempt',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ASSIGNED', 'Assigned'), ('DONE', 'Done')], default='PENDING', max_length=10),
        ),
    ]
