# Generated by Django 4.2.11 on 2024-10-11 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('georeferencing', '0018_rename_created_geoattempt_createddatetime_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='created',
            new_name='createdDateTime',
        ),
    ]
