# Generated by Django 4.2.11 on 2024-10-11 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('georeferencing', '0022_remove_batch_images_batch_feat'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='georeferencing.batch'),
        ),
    ]
