# Generated by Django 4.2.11 on 2024-10-11 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georeferencing', '0024_batch_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='numberImages',
            field=models.IntegerField(default=0),
        ),
    ]
