# Generated by Django 4.2.11 on 2024-10-11 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georeferencing', '0025_batch_numberimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='mission',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
