# Generated by Django 4.2.16 on 2024-10-12 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georeferencing', '0026_batch_mission'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='replicas',
            field=models.IntegerField(default=5),
        ),
    ]
