# Generated by Django 4.2.16 on 2024-10-12 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georeferencing', '0027_batch_replicas'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='largeImageURL',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='smallImageURL',
            field=models.URLField(blank=True, null=True),
        ),
    ]
