# Generated by Django 4.2.16 on 2024-10-12 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georeferencing', '0028_image_largeimageurl_image_smallimageurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='replicas',
            field=models.IntegerField(default=5),
        ),
    ]
