# Generated by Django 4.2.16 on 2024-10-14 20:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('georeferencing', '0029_image_replicas'),
    ]

    operations = [
        migrations.AddField(
            model_name='geoattempt',
            name='assignedUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
