# Generated by Django 4.2.16 on 2024-10-16 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('georeferencing', '0031_batch_fcltge_batch_fcltlt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batch',
            old_name='fcltlt',
            new_name='fcltle',
        ),
    ]
