# Generated by Django 4.2.16 on 2024-10-23 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georeferencing', '0032_rename_fcltlt_batch_fcltle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='fcltge',
            field=models.IntegerField(blank=True, null=True, verbose_name='Focal length >='),
        ),
        migrations.AlterField(
            model_name='batch',
            name='fcltle',
            field=models.IntegerField(blank=True, null=True, verbose_name='Focal length <='),
        ),
    ]
