# Generated by Django 4.2.16 on 2024-10-23 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georeferencing', '0033_alter_batch_fcltge_alter_batch_fcltle'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='originalImages',
            field=models.TextField(blank=True, null=True),
        ),
    ]
