# Generated by Django 4.2.16 on 2024-10-25 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georeferencing', '0034_batch_originalimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='type',
            field=models.CharField(choices=[('SEARCH', 'Search'), ('LIST', 'List')], default='SEARCH', max_length=20),
        ),
        migrations.AlterField(
            model_name='batch',
            name='originalImages',
            field=models.TextField(blank=True, null=True, verbose_name='Original images'),
        ),
    ]
