# Generated by Django 4.2.16 on 2025-04-22 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georeferencing', '0041_rename_geoattemptbyuserbyday_geoattemptsbyuserbyday'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='log',
            field=models.TextField(blank=True, null=True),
        ),
    ]
