# Generated by Django 4.2.16 on 2025-04-23 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georeferencing', '0042_batch_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='processing_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='processing_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='processing_status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='NOT_STARTED', max_length=20, verbose_name='Processing Status'),
        ),
    ]
