# Generated by Django 4.2.16 on 2024-10-16 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='time_spent',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
