# Generated by Django 4.2.16 on 2024-10-16 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_userprofile_time_spent'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='controlPointsDone',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
