# Generated by Django 4.2.16 on 2024-10-16 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_userprofile_controlpointsdone'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cheating',
            field=models.IntegerField(default=0),
        ),
    ]
