# Generated by Django 4.2.16 on 2025-04-19 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_userprofile_country_userprofile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='visible',
            field=models.BooleanField(default=True, help_text='Si está desactivado, tu perfil no aparecerá en los rankings públicos', verbose_name='Visible en rankings'),
        ),
    ]
